apiVersion: v1
kind: Service
metadata:
  name: flm-app-service
  namespace: flm-app
  labels:
    app: flm-app
spec:
  type: NodePort
  selector:
    app: flm-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000